### ISSUE TITLE
Is wtforms-json necessary?

### ISSUE THREAD

**Issue by foxx** [kvesteri/wtforms-json#41]
As a follow up to an issue raised [here](https://github.com/wtforms/wtforms/issues/198), given that the Form constructor in `2.x` now supports the `data` attributes, do we really need `wtforms-json` anymore? At the very least, should there be a notice on the README stating that this library is only required for `1.x`? Have I missed anything at all?

**Comment by alanhamlett** [comment]
Yes, this library is needed. **DO NOT** pass user input as a `kwarg` or using `data` param to a form because it is not validated!

`data` is meant to be used as a backup/default value for a field and is not run against your validators. Also, the value from `obj` takes precedence over `data`, so your api resources won't update your fields with the new value passed in a PUT request if you also pass an existing `obj` to the form.

**Comment by foxx** [comment]
Updated the original issue, thank you for the heads up, I'll go ahead and close this out.
